[pytest]
testpaths = tests
filterwarnings =
    ignore::FutureWarning:yfinance.*
    ignore::FutureWarning:pandas.*
    ignore::DeprecationWarning:pkg_resources.*
    ignore::ResourceWarning
    ignore::RuntimeWarning:unittest.mock.*
    ignore:coroutine.*was never awaited:RuntimeWarning
