"""Shared compounding / fee / timing simulator for MR and futures alpha streams.

Produces monthly equity curves using one set of conventions:
  - one friction assumption per component (round-trip bps)
  - one concurrent-position / slot limit rule for discrete trades
  - one compounding rule (trade-date or month-end)

Inputs
------
MR trades:
    backend/data/mr_trades.csv with entry_date, exit_date, net_pct, [size_mult]
    (generated by backend/scripts/backtest_technicals.py with exit-date capture).

Futures positions:
    analysis_output/signal_engine_*.csv produced by
    signal-engine/scripts/capture_for_shared_simulator.py.

Outputs
-------
    analysis_output/shared_mr_equity.csv
    analysis_output/shared_futures_equity.csv
    analysis_output/shared_reconciliation.csv

"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd

HERE = Path(__file__).parent.resolve()
BACKEND = HERE.parent
ROOT = BACKEND.parent
sys.path.insert(0, str(BACKEND))

DATA_DIR = BACKEND / "data"
OUT_DIR = ROOT / "analysis_output"
OUT_DIR.mkdir(parents=True, exist_ok=True)


def _monthly_from_daily(daily_equity: pd.Series) -> pd.Series:
    """Convert a daily equity curve to month-end net returns."""
    me = daily_equity.resample("ME").last().ffill()
    return me.pct_change(fill_method=None).dropna().rename("net_pct")


def simulate_mr_trades(
    trades: pd.DataFrame,
    max_concurrent: int = 5,
    friction_pct: float = 0.0,
    use_gross: bool = False,
    tbill_rate: float = 0.0,
    vol_target: float | None = None,
) -> dict:
    """Simulate a concurrent-slot MR book from discrete trades.

    Parameters mirror ``run_portfolio_simulation`` in backtest_technicals.py
    but use real entry/exit dates instead of the imputed ``exit_day`` approximation.

    By default the simulator uses the project's own ``net_pct`` (the original engine's
    net-of-friction trade return, which already embeds the 0.5% round-trip cost).  If
    ``use_gross`` is True and a ``gross_pct`` column exists, the supplied
    ``friction_pct`` round-trip drag is subtracted from the gross return.  ``tbill_rate``
    controls idle-cash yield; set to 0.0 to match the current project default where
    idle capital earns nothing.

    Returns
    -------
    dict with equity (daily Series), equity_log (list of tuples), monthly returns.
    """
    df = trades.copy().sort_values("entry_date").reset_index(drop=True)
    required = {"entry_date", "exit_date", "net_pct"}
    if not required.issubset(df.columns):
        raise ValueError(f"MR trades must contain {required}, got {set(df.columns)}")

    df["entry_date"] = pd.to_datetime(df["entry_date"])
    df["exit_date"] = pd.to_datetime(df["exit_date"])

    if use_gross and "gross_pct" in df.columns:
        df["sim_pct"] = df["gross_pct"] - friction_pct
    else:
        df["sim_pct"] = df["net_pct"]

    slot_size = 1.0 / max_concurrent
    capital = 10_000.0
    peak = capital
    max_dd = 0.0
    open_slots: list[tuple[pd.Timestamp, float, float]] = []
    equity_log: list[tuple[pd.Timestamp, float]] = [(df["entry_date"].iloc[0], capital)]
    skipped = 0
    last_event_dt = df["entry_date"].iloc[0]

    # Vol targeting (optional, expanding realised vol of per-trade net_pct).
    _vol_multipliers: list[float] | None = None
    if vol_target is not None and len(df) >= 2:
        _min_periods = min(21, len(df) - 1)
        _roll_std = df["sim_pct"].shift(1).rolling(window=63, min_periods=_min_periods).std()
        _exp_std = df["sim_pct"].shift(1).expanding(min_periods=_min_periods).std()
        _realized_std = _roll_std.fillna(_exp_std)
        # sim_pct is in percent, so divide by 100 to get decimal vol.
        _forecast_vol = ((_realized_std / 100.0) * np.sqrt(252 / 10)).clip(lower=1e-6)
        _multiplier = (vol_target / _forecast_vol).clip(lower=0.25, upper=2.0)
        _vol_multipliers = _multiplier.fillna(1.0).tolist()

    def _apply_tbill(until_dt: pd.Timestamp) -> None:
        """Credit T-bill return on idle slots between last_event_dt and until_dt."""
        nonlocal capital, last_event_dt
        if tbill_rate <= 0:
            last_event_dt = until_dt
            return
        dt_days = (until_dt - last_event_dt).days
        if dt_days <= 0:
            return
        idle_slots = max_concurrent - len(open_slots)
        if idle_slots <= 0:
            return
        idle_frac = idle_slots / max_concurrent
        capital *= 1.0 + tbill_rate * idle_frac * (dt_days / 365.25)
        last_event_dt = until_dt

    for i, row in df.iterrows():
        entry_dt = row["entry_date"]
        exit_dt = row["exit_date"]
        sim_pct = float(row["sim_pct"])

        _apply_tbill(entry_dt)

        still_open = []
        for slot_exit, slot_pct, slot_mult in sorted(open_slots, key=lambda x: x[0]):
            if slot_exit <= entry_dt:
                capital += capital * slot_size * slot_mult * (slot_pct / 100)
                peak = max(peak, capital)
                max_dd = max(max_dd, (peak - capital) / peak * 100)
                equity_log.append((slot_exit, round(capital, 4)))
            else:
                still_open.append((slot_exit, slot_pct, slot_mult))
        open_slots = still_open

        if len(open_slots) < max_concurrent:
            _trade_size = float(row.get("size_mult", 1.0)) if pd.notna(row.get("size_mult")) else 1.0
            _vol_mult = _vol_multipliers[i] if _vol_multipliers else 1.0
            _mult = _trade_size * _vol_mult
            open_slots.append((exit_dt, sim_pct, _mult))
        else:
            skipped += 1

    for slot_exit, slot_pct, slot_mult in sorted(open_slots, key=lambda x: x[0]):
        _apply_tbill(slot_exit)
        capital += capital * slot_size * slot_mult * (slot_pct / 100)
        peak = max(peak, capital)
        max_dd = max(max_dd, (peak - capital) / peak * 100)
        equity_log.append((slot_exit, round(capital, 4)))

    equity = pd.DataFrame(equity_log, columns=["date", "equity"]).set_index("date")["equity"].sort_index()
    monthly = _monthly_from_daily(equity)

    return {
        "equity": equity,
        "equity_log": equity_log,
        "monthly": monthly,
        "skipped": skipped,
        "max_dd": max_dd,
    }


def simulate_futures_positions(
    per_instrument_returns: pd.DataFrame,
    friction_bps: float = 0.0,
    capital: float = 1.0,
) -> dict:
    """Simulate a futures-style portfolio from per-instrument daily net returns.

    The per-instrument returns already embed the signal-engine's vol-target,
    IDM, buffering and per-side cost assumptions.  This function just performs
    the portfolio-level combination (sum across instruments), applies a
    shared round-trip friction assumption to turnover, and compounds.

    Parameters
    ----------
    per_instrument_returns: DataFrame of daily net returns per instrument
        (as fraction of capital, e.g. 0.001 for 10 bps).
    friction_bps: additional round-trip bps charged on daily traded notional.
        The signal-engine's own per-side costs are already in the input.
    capital: starting capital (default 1.0 for a normalized equity curve).

    Returns
    -------
    dict with daily equity, daily returns, monthly returns.
    """
    pir = per_instrument_returns.sort_index().dropna(how="all")
    daily_gross = pir.sum(axis=1)

    # Optional extra friction: estimate turnover from return changes (rough proxy)
    # and charge round-trip bps.  If no extra friction is requested, return is
    # just the sum of the per-instrument returns.
    if friction_bps:
        # Proxy for daily traded notional: absolute change in portfolio return.
        turnover_proxy = daily_gross.diff().abs().fillna(0.0)
        cost = turnover_proxy * (friction_bps / 1e4)
    else:
        cost = 0.0

    daily_net = daily_gross - cost
    equity = capital * (1.0 + daily_net).cumprod()
    monthly = _monthly_from_daily(equity)

    return {
        "equity": equity,
        "daily_returns": daily_net,
        "monthly": monthly,
    }


def main() -> None:
    mr_csv = DATA_DIR / "mr_trades.csv"
    if not mr_csv.exists():
        raise SystemExit(f"Missing {mr_csv} — run backtest_technicals.py first.")

    trades = pd.read_csv(mr_csv)
    print(f"Loaded {len(trades)} MR trades.")
    if {"entry_date", "exit_date"}.issubset(trades.columns):
        # Match the project's original portfolio simulation conventions:
        # MAX_PORTFOLIO_SLOTS=5, net-of-friction returns, no idle-cash yield.
        mr_res = simulate_mr_trades(
            trades,
            max_concurrent=5,
            friction_pct=0.0,
            use_gross=False,
            tbill_rate=0.0,
        )
        mr_res["monthly"].to_csv(OUT_DIR / "shared_mr_equity.csv", header=["net_pct"])
        print(f"Wrote shared MR monthly equity ({len(mr_res['monthly'])} months).")
    else:
        print("mr_trades.csv missing entry_date/exit_date; skipping MR (re-run backtest_technicals.py).")

    pir_csv = OUT_DIR / "signal_engine_per_instrument_returns.csv"
    if pir_csv.exists():
        pir = pd.read_csv(pir_csv, index_col=0, parse_dates=True)
        fut_res = simulate_futures_positions(pir, friction_bps=0.0, capital=1.0)
        fut_res["monthly"].to_csv(OUT_DIR / "shared_futures_equity.csv", header=["net_pct"])
        print(f"Wrote shared futures monthly equity ({len(fut_res['monthly'])} months).")
    else:
        print(f"Skipping futures — missing {pir_csv}.")


if __name__ == "__main__":
    main()
