"""add_tsys_remaining_tables

Revision ID: 5864d5cdab47
Revises: 6956c0e1988d
Create Date: 2026-06-07 22:51:00.467142

"""

from typing import Union
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5864d5cdab47"
down_revision: Union[str, Sequence[str], None] = "6956c0e1988d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "calibration_history",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("version", sa.String(length=20), nullable=False),
        sa.Column("calibration_data", sa.JSON(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "corporate_action_validations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ticker", sa.String(length=12), nullable=False),
        sa.Column("action_type", sa.String(length=20), nullable=False),
        sa.Column("execution_date", sa.Date(), nullable=False),
        sa.Column("polygon_value", sa.Float(), nullable=True),
        sa.Column("yfinance_value", sa.Float(), nullable=True),
        sa.Column("is_valid", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("discrepancy_details", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "data_retention_rules",
        sa.Column("table_name", sa.String(length=100), nullable=False),
        sa.Column("retention_days", sa.Integer(), nullable=False),
        sa.Column("anonymize", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("table_name"),
    )
    op.create_table(
        "gate_registry",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("owner", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="active", nullable=False),
        sa.Column("test_coverage", sa.Float(), server_default="0.0", nullable=False),
        sa.Column("live_validation_status", sa.String(length=50), nullable=True),
        sa.Column("retirement_criteria", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "incident_timeline",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("severity", sa.String(length=10), server_default="info", nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "model_registry",
        sa.Column("model_id", sa.String(length=100), nullable=False),
        sa.Column("training_data_hash", sa.String(length=64), nullable=False),
        sa.Column("feature_schema_hash", sa.String(length=64), nullable=False),
        sa.Column("hyperparameters", sa.JSON(), nullable=True),
        sa.Column("metrics", sa.JSON(), nullable=True),
        sa.Column("approval_decision", sa.String(length=20), server_default="pending", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("model_id"),
    )
    op.create_table(
        "outcome_resolver_audits",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("signals_processed", sa.Integer(), server_default="0", nullable=False),
        sa.Column("signals_resolved", sa.Integer(), server_default="0", nullable=False),
        sa.Column("price_source", sa.String(length=50), nullable=True),
        sa.Column("missing_bars_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("corrections_applied", sa.JSON(), nullable=True),
        sa.Column("unresolved_reasons", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "provider_health_scorecards",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("endpoint", sa.String(length=255), nullable=False),
        sa.Column("latency_avg_ms", sa.Float(), server_default="0.0", nullable=False),
        sa.Column("error_rate", sa.Float(), server_default="0.0", nullable=False),
        sa.Column("stale_data_rate", sa.Float(), server_default="0.0", nullable=False),
        sa.Column("schema_drift_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("health_score", sa.Float(), server_default="100.0", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("last_updated", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "provider_response_samples",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("endpoint", sa.String(length=255), nullable=False),
        sa.Column("ticker", sa.String(length=12), nullable=True),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("latency_ms", sa.Float(), nullable=True),
        sa.Column("response_body", sa.Text(), nullable=False),
        sa.Column("is_drifted", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("drift_details", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "signal_policies",
        sa.Column("version", sa.String(length=20), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("version"),
    )
    op.create_table(
        "action_audit_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column("ip_address", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_action_audit_logs_user_id"), "action_audit_logs", ["user_id"], unique=False)
    op.create_table(
        "model_shadow_scores",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("signal_id", sa.Integer(), nullable=False),
        sa.Column("model_id", sa.String(length=100), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("champion_score", sa.Float(), nullable=False),
        sa.Column("champion_confidence", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["signal_id"], ["signals.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_model_shadow_scores_signal_id"), "model_shadow_scores", ["signal_id"], unique=False)
    op.create_table(
        "outcome_path_snapshots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("signal_id", sa.Integer(), nullable=False),
        sa.Column("path_data", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["signal_id"], ["signals.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_outcome_path_snapshots_signal_id"), "outcome_path_snapshots", ["signal_id"], unique=False)
    op.create_table(
        "signal_gate_traces",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("signal_id", sa.Integer(), nullable=False),
        sa.Column("gate_id", sa.String(length=50), nullable=False),
        sa.Column("version", sa.String(length=20), nullable=False),
        sa.Column("input_values", sa.JSON(), nullable=True),
        sa.Column("score_delta", sa.Float(), server_default="0.0", nullable=False),
        sa.Column("confidence_delta", sa.Float(), server_default="0.0", nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["signal_id"], ["signals.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_signal_gate_traces_signal_id"), "signal_gate_traces", ["signal_id"], unique=False)
    op.add_column("signals", sa.Column("policy_version", sa.String(length=20), nullable=True))
    op.add_column("users", sa.Column("max_daily_orders", sa.Integer(), nullable=True))
    op.add_column("users", sa.Column("max_daily_loss", sa.Float(), nullable=True))
    op.add_column("users", sa.Column("max_open_positions", sa.Integer(), nullable=True))
    op.add_column("users", sa.Column("max_ticker_notional", sa.Float(), nullable=True))
    op.add_column("users", sa.Column("max_sector_exposure", sa.Float(), nullable=True))
    op.add_column("users", sa.Column("alpaca_key_version", sa.Integer(), server_default="1", nullable=False))
    op.add_column("users", sa.Column("risk_acknowledged", sa.Boolean(), server_default="0", nullable=False))
    op.add_column("users", sa.Column("risk_acknowledged_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "risk_acknowledged_at")
    op.drop_column("users", "risk_acknowledged")
    op.drop_column("users", "alpaca_key_version")
    op.drop_column("users", "max_sector_exposure")
    op.drop_column("users", "max_ticker_notional")
    op.drop_column("users", "max_open_positions")
    op.drop_column("users", "max_daily_loss")
    op.drop_column("users", "max_daily_orders")
    op.drop_column("signals", "policy_version")
    op.drop_index(op.f("ix_signal_gate_traces_signal_id"), table_name="signal_gate_traces")
    op.drop_table("signal_gate_traces")
    op.drop_index(op.f("ix_outcome_path_snapshots_signal_id"), table_name="outcome_path_snapshots")
    op.drop_table("outcome_path_snapshots")
    op.drop_index(op.f("ix_model_shadow_scores_signal_id"), table_name="model_shadow_scores")
    op.drop_table("model_shadow_scores")
    op.drop_index(op.f("ix_action_audit_logs_user_id"), table_name="action_audit_logs")
    op.drop_table("action_audit_logs")
    op.drop_table("signal_policies")
    op.drop_table("provider_response_samples")
    op.drop_table("provider_health_scorecards")
    op.drop_table("outcome_resolver_audits")
    op.drop_table("model_registry")
    op.drop_table("incident_timeline")
    op.drop_table("gate_registry")
    op.drop_table("data_retention_rules")
    op.drop_table("corporate_action_validations")
    op.drop_table("calibration_history")
    # ### end Alembic commands ###
