"""add_auth_improvements

Revision ID: b908e650076c
Revises: c9a1f3e7d2b4
Create Date: 2026-06-07 22:23:23.601495

"""

from typing import Union
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b908e650076c"
down_revision: Union[str, Sequence[str], None] = "c9a1f3e7d2b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "oauth_one_time_codes",
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("access_token", sa.String(length=500), nullable=False),
        sa.Column("user_data", sa.JSON(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_index(op.f("ix_oauth_one_time_codes_code"), "oauth_one_time_codes", ["code"], unique=False)
    op.create_table(
        "oauth_states",
        sa.Column("state", sa.String(length=64), nullable=False),
        sa.Column("referred_by", sa.Integer(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("state"),
    )
    op.create_index(op.f("ix_oauth_states_state"), "oauth_states", ["state"], unique=False)
    op.create_table(
        "auth_audit_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("event", sa.String(length=50), nullable=False),
        sa.Column("ip_address", sa.String(length=50), nullable=True),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_auth_audit_logs_email"), "auth_audit_logs", ["email"], unique=False)
    op.create_index(op.f("ix_auth_audit_logs_user_id"), "auth_audit_logs", ["user_id"], unique=False)
    op.create_table(
        "email_change_requests",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("old_email", sa.String(length=255), nullable=False),
        sa.Column("new_email", sa.String(length=255), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_email_change_requests_token_hash"), "email_change_requests", ["token_hash"], unique=True)
    op.create_index(op.f("ix_email_change_requests_user_id"), "email_change_requests", ["user_id"], unique=False)
    op.alter_column(
        "broker_orders", "status", existing_type=sa.VARCHAR(length=20), server_default=None, existing_nullable=False
    )
    op.create_index(op.f("ix_broker_orders_created_at"), "broker_orders", ["created_at"], unique=False)
    op.add_column("refresh_tokens", sa.Column("user_agent", sa.String(length=255), nullable=True))
    op.add_column("refresh_tokens", sa.Column("ip_address", sa.String(length=50), nullable=True))
    op.create_index(op.f("ix_send_log_created_at"), "send_log", ["created_at"], unique=False)
    op.create_index(op.f("ix_signals_created_at"), "signals", ["created_at"], unique=False)
    op.add_column("users", sa.Column("failed_login_attempts", sa.Integer(), server_default="0", nullable=False))
    op.add_column("users", sa.Column("lockout_until", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "lockout_until")
    op.drop_column("users", "failed_login_attempts")
    op.drop_index(op.f("ix_signals_created_at"), table_name="signals")
    op.drop_index(op.f("ix_send_log_created_at"), table_name="send_log")
    op.drop_column("refresh_tokens", "ip_address")
    op.drop_column("refresh_tokens", "user_agent")
    op.drop_index(op.f("ix_broker_orders_created_at"), table_name="broker_orders")
    op.alter_column(
        "broker_orders",
        "status",
        existing_type=sa.VARCHAR(length=20),
        server_default=sa.text("'submitted'::character varying"),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_email_change_requests_user_id"), table_name="email_change_requests")
    op.drop_index(op.f("ix_email_change_requests_token_hash"), table_name="email_change_requests")
    op.drop_table("email_change_requests")
    op.drop_index(op.f("ix_auth_audit_logs_user_id"), table_name="auth_audit_logs")
    op.drop_index(op.f("ix_auth_audit_logs_email"), table_name="auth_audit_logs")
    op.drop_table("auth_audit_logs")
    op.drop_index(op.f("ix_oauth_states_state"), table_name="oauth_states")
    op.drop_table("oauth_states")
    op.drop_index(op.f("ix_oauth_one_time_codes_code"), table_name="oauth_one_time_codes")
    op.drop_table("oauth_one_time_codes")
    # ### end Alembic commands ###
