"""add_webhook_secret_to_user

Revision ID: 283e4d8a51c4
Revises: 24708898b1fb
Create Date: 2026-06-07 22:44:16.313015

"""

from typing import Union
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "283e4d8a51c4"
down_revision: Union[str, Sequence[str], None] = "24708898b1fb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("webhook_secret", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "webhook_secret")
    # ### end Alembic commands ###
