"""add_stripe_event_audit_columns

Revision ID: e6e2a62ee387
Revises: b908e650076c
Create Date: 2026-06-07 22:41:43.892351

"""

from typing import Union
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e6e2a62ee387"
down_revision: Union[str, Sequence[str], None] = "b908e650076c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("stripe_events", sa.Column("customer_id", sa.String(length=64), nullable=True))
    op.add_column("stripe_events", sa.Column("subscription_id", sa.String(length=64), nullable=True))
    op.add_column("stripe_events", sa.Column("event_type", sa.String(length=64), nullable=True))
    op.add_column("stripe_events", sa.Column("transition", sa.String(length=100), nullable=True))
    op.add_column("stripe_events", sa.Column("handler_result", sa.Text(), nullable=True))
    op.add_column("stripe_events", sa.Column("is_replay", sa.Boolean(), server_default="0", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stripe_events", "is_replay")
    op.drop_column("stripe_events", "handler_result")
    op.drop_column("stripe_events", "transition")
    op.drop_column("stripe_events", "event_type")
    op.drop_column("stripe_events", "subscription_id")
    op.drop_column("stripe_events", "customer_id")
    # ### end Alembic commands ###
