"""add_auto_execute_fields_to_users

Revision ID: 05fadc671532
Revises: 7a9277e42dc3
Create Date: 2026-05-26 08:55:36.083698

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "05fadc671532"
down_revision: Union[str, Sequence[str], None] = "7a9277e42dc3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "password_reset_tokens",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("used", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_password_reset_tokens_email"), "password_reset_tokens", ["email"], unique=False)
    op.create_index(op.f("ix_password_reset_tokens_token_hash"), "password_reset_tokens", ["token_hash"], unique=True)
    op.create_table(
        "stripe_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event_id", sa.String(length=64), nullable=False),
        sa.Column("processed_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_stripe_events_event_id"), "stripe_events", ["event_id"], unique=True)
    op.create_table(
        "signal_alerts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("ticker", sa.String(length=10), nullable=False),
        sa.Column("min_confidence", sa.Float(), nullable=False),
        sa.Column("action_filter", sa.String(length=10), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_signal_alerts_ticker"), "signal_alerts", ["ticker"], unique=False)
    op.create_index(op.f("ix_signal_alerts_user_id"), "signal_alerts", ["user_id"], unique=False)
    op.add_column("performance_snapshots", sa.Column("alpha", sa.Float(), nullable=True))
    op.add_column("users", sa.Column("auto_execute", sa.Boolean(), server_default="0", nullable=False))
    op.add_column("users", sa.Column("auto_execute_min_conf", sa.Float(), nullable=True))
    op.add_column("users", sa.Column("auto_execute_broker", sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "auto_execute_broker")
    op.drop_column("users", "auto_execute_min_conf")
    op.drop_column("users", "auto_execute")
    op.drop_column("performance_snapshots", "alpha")
    op.drop_index(op.f("ix_signal_alerts_user_id"), table_name="signal_alerts")
    op.drop_index(op.f("ix_signal_alerts_ticker"), table_name="signal_alerts")
    op.drop_table("signal_alerts")
    op.drop_index(op.f("ix_stripe_events_event_id"), table_name="stripe_events")
    op.drop_table("stripe_events")
    op.drop_index(op.f("ix_password_reset_tokens_token_hash"), table_name="password_reset_tokens")
    op.drop_index(op.f("ix_password_reset_tokens_email"), table_name="password_reset_tokens")
    op.drop_table("password_reset_tokens")
    # ### end Alembic commands ###
