"""add_tsys4_columns_and_tables

Revision ID: 6956c0e1988d
Revises: 283e4d8a51c4
Create Date: 2026-06-07 22:47:06.077236

"""

from typing import Union
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6956c0e1988d"
down_revision: Union[str, Sequence[str], None] = "283e4d8a51c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "background_job_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_name", sa.String(length=100), nullable=False),
        sa.Column("cycle_id", sa.String(length=100), nullable=True),
        sa.Column("start_time", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("duration_s", sa.Float(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("worker_id", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_background_job_runs_cycle_id"), "background_job_runs", ["cycle_id"], unique=False)
    op.create_table(
        "provider_telemetry",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("cycle_id", sa.String(length=100), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("api_calls", sa.Integer(), nullable=False),
        sa.Column("cache_hits", sa.Integer(), nullable=False),
        sa.Column("cache_misses", sa.Integer(), nullable=False),
        sa.Column("quota_remaining", sa.Integer(), nullable=True),
        sa.Column("throttles", sa.Integer(), nullable=False),
        sa.Column("fallback_usage", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_provider_telemetry_cycle_id"), "provider_telemetry", ["cycle_id"], unique=False)
    op.add_column("broker_orders", sa.Column("cycle_id", sa.String(length=100), nullable=True))
    op.create_index(op.f("ix_broker_orders_cycle_id"), "broker_orders", ["cycle_id"], unique=False)
    op.add_column("send_log", sa.Column("cycle_id", sa.String(length=100), nullable=True))
    op.create_index(op.f("ix_send_log_cycle_id"), "send_log", ["cycle_id"], unique=False)
    op.add_column("signal_deliveries", sa.Column("cycle_id", sa.String(length=100), nullable=True))
    op.create_index(op.f("ix_signal_deliveries_cycle_id"), "signal_deliveries", ["cycle_id"], unique=False)
    op.add_column("signals", sa.Column("cycle_id", sa.String(length=100), nullable=True))
    op.create_index(op.f("ix_signals_cycle_id"), "signals", ["cycle_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_signals_cycle_id"), table_name="signals")
    op.drop_column("signals", "cycle_id")
    op.drop_index(op.f("ix_signal_deliveries_cycle_id"), table_name="signal_deliveries")
    op.drop_column("signal_deliveries", "cycle_id")
    op.drop_index(op.f("ix_send_log_cycle_id"), table_name="send_log")
    op.drop_column("send_log", "cycle_id")
    op.drop_index(op.f("ix_broker_orders_cycle_id"), table_name="broker_orders")
    op.drop_column("broker_orders", "cycle_id")
    op.drop_index(op.f("ix_provider_telemetry_cycle_id"), table_name="provider_telemetry")
    op.drop_table("provider_telemetry")
    op.drop_index(op.f("ix_background_job_runs_cycle_id"), table_name="background_job_runs")
    op.drop_table("background_job_runs")
    # ### end Alembic commands ###
