"""initial_schema

Revision ID: 7a9277e42dc3
Revises:
Create Date: 2026-05-26 08:26:52.341728

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7a9277e42dc3"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "password_reset_tokens",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("used", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_password_reset_tokens_email"), "password_reset_tokens", ["email"], unique=False)
    op.create_index(op.f("ix_password_reset_tokens_token_hash"), "password_reset_tokens", ["token_hash"], unique=True)
    op.create_table(
        "performance_snapshots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tag", sa.String(length=120), nullable=False),
        sa.Column("git_sha", sa.String(length=40), nullable=True),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("n_trades", sa.Integer(), nullable=False),
        sa.Column("win_rate", sa.Float(), nullable=True),
        sa.Column("sharpe", sa.Float(), nullable=True),
        sa.Column("alpha", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_performance_snapshots_tag"), "performance_snapshots", ["tag"], unique=False)
    op.create_table(
        "send_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("time", sa.String(length=8), nullable=True),
        sa.Column("status", sa.String(length=10), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "signals",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ticker", sa.String(length=10), nullable=False),
        sa.Column("company", sa.String(length=100), nullable=True),
        sa.Column("action", sa.String(length=4), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("change", sa.Float(), nullable=True),
        sa.Column("change_pct", sa.Float(), nullable=True),
        sa.Column("entry", sa.Float(), nullable=True),
        sa.Column("stop", sa.Float(), nullable=True),
        sa.Column("target", sa.Float(), nullable=True),
        sa.Column("rr", sa.String(length=10), nullable=True),
        sa.Column("headline", sa.Text(), nullable=False),
        sa.Column("sentiment", sa.Float(), nullable=True),
        sa.Column("style", sa.String(length=20), nullable=True),
        sa.Column("sources", sa.JSON(), nullable=True),
        sa.Column("rationale", sa.JSON(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_sent", sa.Boolean(), nullable=True),
        sa.Column("is_skipped", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.Column("sent_at", sa.DateTime(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("reviewed", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("confidence_warning", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("plain_english", sa.JSON(), nullable=True),
        sa.Column("session", sa.String(length=20), nullable=True),
        sa.Column("days_to_earnings", sa.Integer(), nullable=True),
        sa.Column("next_earnings_date", sa.String(length=20), nullable=True),
        sa.Column("sector_etf", sa.String(length=10), nullable=True),
        sa.Column("rs_vs_sector", sa.Float(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("outcome_pct", sa.Float(), nullable=True),
        sa.Column("outcome_at", sa.DateTime(), nullable=True),
        sa.Column("outcome_1d", sa.Float(), nullable=True),
        sa.Column("outcome_3d", sa.Float(), nullable=True),
        sa.Column("outcome_14d", sa.Float(), nullable=True),
        sa.Column("hit_stop", sa.Boolean(), nullable=True),
        sa.Column("hit_target", sa.Boolean(), nullable=True),
        sa.Column("mae", sa.Float(), nullable=True),
        sa.Column("mfe", sa.Float(), nullable=True),
        sa.Column("exit_type", sa.String(length=10), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_signals_ticker"), "signals", ["ticker"], unique=False)
    op.create_table(
        "sources",
        sa.Column("id", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("abbr", sa.String(length=6), nullable=True),
        sa.Column("is_on", sa.Boolean(), nullable=True),
        sa.Column("requests_24h", sa.Integer(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("feed", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "stripe_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event_id", sa.String(length=64), nullable=False),
        sa.Column("processed_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_stripe_events_event_id"), "stripe_events", ["event_id"], unique=True)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_owner", sa.Boolean(), nullable=True),
        sa.Column("telegram_chat_id", sa.String(length=50), nullable=True),
        sa.Column("telegram_link_code", sa.String(length=20), nullable=True),
        sa.Column("stripe_customer_id", sa.String(length=50), nullable=True),
        sa.Column("stripe_subscription_id", sa.String(length=50), nullable=True),
        sa.Column("subscription_tier", sa.String(length=20), nullable=True),
        sa.Column("subscription_status", sa.String(length=20), nullable=True),
        sa.Column("subscription_period_end", sa.DateTime(), nullable=True),
        sa.Column("min_confidence_override", sa.Float(), nullable=True),
        sa.Column("referred_by", sa.Integer(), nullable=True),
        sa.Column("referral_rewarded", sa.Boolean(), nullable=True),
        sa.Column("oauth_provider", sa.String(length=20), nullable=True),
        sa.Column("oauth_sub", sa.String(length=255), nullable=True),
        sa.Column("email_verified", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("email_verify_token", sa.String(length=64), nullable=True),
        sa.Column("webhook_url", sa.String(length=500), nullable=True),
        sa.Column("discord_webhook_url", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["referred_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("oauth_sub"),
        sa.UniqueConstraint("telegram_link_code"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_email_verify_token"), "users", ["email_verify_token"], unique=True)
    op.create_table(
        "watchlist",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ticker", sa.String(length=10), nullable=False),
        sa.Column("company", sa.String(length=100), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("added_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ticker"),
    )
    op.create_table(
        "price_alerts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("ticker", sa.String(length=10), nullable=False),
        sa.Column("target_price", sa.Float(), nullable=False),
        sa.Column("condition", sa.String(length=10), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_price_alerts_ticker"), "price_alerts", ["ticker"], unique=False)
    op.create_index(op.f("ix_price_alerts_user_id"), "price_alerts", ["user_id"], unique=False)
    op.create_table(
        "push_subscriptions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("endpoint", sa.Text(), nullable=False),
        sa.Column("p256dh", sa.String(length=100), nullable=False),
        sa.Column("auth", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("endpoint"),
    )
    op.create_index(op.f("ix_push_subscriptions_user_id"), "push_subscriptions", ["user_id"], unique=False)
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)
    op.create_table(
        "signal_alerts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("ticker", sa.String(length=10), nullable=False),
        sa.Column("min_confidence", sa.Float(), nullable=False),
        sa.Column("action_filter", sa.String(length=10), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_signal_alerts_ticker"), "signal_alerts", ["ticker"], unique=False)
    op.create_index(op.f("ix_signal_alerts_user_id"), "signal_alerts", ["user_id"], unique=False)
    op.create_table(
        "signal_deliveries",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("signal_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("sent_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.Column("telegram_msg_id", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(["signal_id"], ["signals.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_signal_deliveries_signal_id"), "signal_deliveries", ["signal_id"], unique=False)
    op.create_index(op.f("ix_signal_deliveries_user_id"), "signal_deliveries", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_signal_deliveries_user_id"), table_name="signal_deliveries")
    op.drop_index(op.f("ix_signal_deliveries_signal_id"), table_name="signal_deliveries")
    op.drop_table("signal_deliveries")
    op.drop_index(op.f("ix_signal_alerts_user_id"), table_name="signal_alerts")
    op.drop_index(op.f("ix_signal_alerts_ticker"), table_name="signal_alerts")
    op.drop_table("signal_alerts")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(op.f("ix_push_subscriptions_user_id"), table_name="push_subscriptions")
    op.drop_table("push_subscriptions")
    op.drop_index(op.f("ix_price_alerts_user_id"), table_name="price_alerts")
    op.drop_index(op.f("ix_price_alerts_ticker"), table_name="price_alerts")
    op.drop_table("price_alerts")
    op.drop_table("watchlist")
    op.drop_index(op.f("ix_users_email_verify_token"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_stripe_events_event_id"), table_name="stripe_events")
    op.drop_table("stripe_events")
    op.drop_table("sources")
    op.drop_index(op.f("ix_signals_ticker"), table_name="signals")
    op.drop_table("signals")
    op.drop_table("send_log")
    op.drop_index(op.f("ix_performance_snapshots_tag"), table_name="performance_snapshots")
    op.drop_table("performance_snapshots")
    op.drop_index(op.f("ix_password_reset_tokens_token_hash"), table_name="password_reset_tokens")
    op.drop_index(op.f("ix_password_reset_tokens_email"), table_name="password_reset_tokens")
    op.drop_table("password_reset_tokens")
    op.drop_table("app_settings")
    # ### end Alembic commands ###
