"""add_unified_delivery_receipt_columns

Revision ID: 24708898b1fb
Revises: e6e2a62ee387
Create Date: 2026-06-07 22:43:01.002340

"""

from typing import Union
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "24708898b1fb"
down_revision: Union[str, Sequence[str], None] = "e6e2a62ee387"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "signal_deliveries", sa.Column("channel", sa.String(length=20), server_default="telegram", nullable=False)
    )
    op.add_column("signal_deliveries", sa.Column("status", sa.String(length=20), server_default="sent", nullable=False))
    op.add_column("signal_deliveries", sa.Column("retry_count", sa.Integer(), server_default="0", nullable=False))
    op.add_column("signal_deliveries", sa.Column("latency_ms", sa.Float(), nullable=True))
    op.add_column("signal_deliveries", sa.Column("error_code", sa.String(length=50), nullable=True))
    op.add_column("signal_deliveries", sa.Column("dedupe_key", sa.String(length=150), nullable=True))
    op.add_column("signal_deliveries", sa.Column("provider_message_id", sa.String(length=100), nullable=True))
    op.alter_column("signal_deliveries", "signal_id", existing_type=sa.INTEGER(), nullable=True)
    op.create_index(op.f("ix_signal_deliveries_dedupe_key"), "signal_deliveries", ["dedupe_key"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_signal_deliveries_dedupe_key"), table_name="signal_deliveries")
    op.alter_column("signal_deliveries", "signal_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_column("signal_deliveries", "provider_message_id")
    op.drop_column("signal_deliveries", "dedupe_key")
    op.drop_column("signal_deliveries", "error_code")
    op.drop_column("signal_deliveries", "latency_ms")
    op.drop_column("signal_deliveries", "retry_count")
    op.drop_column("signal_deliveries", "status")
    op.drop_column("signal_deliveries", "channel")
    # ### end Alembic commands ###
